openapi: 3.0.0
info:
  title: "[example] Test API"
  version: "1.0.0"
  description: "This API is used to retrieve a list of users."
  contact:
    name: "API Support"
    email: "support@example.com"
servers:
  - url: "https://localhost:3001"
paths:
  /users:
    get:
      summary: "Retrieve a list of users"
      description: "Retrieves a list of users from the database."
      responses:
        '200':
          description: "A list of users"
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
